- README.md
> chore: add requirements section in the README

- opencve/models/cwe.py
- opencve/templates/cwes.html
- tests/test_models.py
> fix: wrong links for CWE definitions

- opencve/context.py
- opencve/controllers/cves.py
- opencve/controllers/home.py
- opencve/static/css/custom.css
- opencve/templates/cve.html
- opencve/templates/cves.html
- opencve/templates/emails/report_message.html
- opencve/templates/home.html
- opencve/templates/report.html
- setup.py
- tests/conftest.py
- tests/controllers/test_cves.py
- tests/data/cves/CVE-2019-17052.json
- tests/data/cves/CVE-2019-8075.json
- tests/data/cves/CVE-2020-27781.json
- tests/data/cves/CVE-2020-29660.json
- tests/data/cves/CVE-2020-35076.json
The CVSS scoring was custom, now it's aligned with official definition : https://nvd.nist.gov/vuln-metrics/cvss
```
None | 0.0
Low | 0.1-3.9
Medium | 4.0-6.9
High | 7.0-8.9
Critical | 9.0-10.0
```
This PR closes #28 and closes #30
> feat: add the NONE and CRITICAL CVSSv3 filters

- opencve/tasks/reports.py
- tests/tasks/test_reports.py
> fix: handle exception in case of bad SMTP configuration

- opencve/admin.py
- opencve/models/users.py
- opencve/settings.py
> fix: user creation/edition in administration panel

- opencve/controllers/cves.py
- opencve/static/css/custom.css
- opencve/templates/cve.html
- opencve/utils.py
- tests/test_utils.py
> feat: display vulnerability type with the CWE ID

- opencve/admin.py
- opencve/templates/admin/index.html
> feat: add more statistics in admin dashboard

- .github/workflows/tests.yml
- README.md
- opencve/controllers/cves.py
- opencve/migrations/versions/33cd640e1112_add_indexes_on_cves_summary_and_cve_cve_.py
- opencve/models/cve.py
- opencve/templates/cves.html
- tests/README.md
- the search function now searches for a matching CVE ID, vendor or a
product
- searching in the description has also been made case-insensitive
All in all, the changes result in increased accuracy of the results ~~without adding a noticeable amount of delay to the searches.~~
> Improved search functionality on /cve

- tests/controllers/test_subscriptions.py
Hello, I am interested on working on this project and wanted to write some tests to gain a better understanding of the existing code and also increase the coverage of the subscriptions controller. These tests simulate the AJAX post requests that happen when the "Subscribe" button is pressed for a vendor or product and check for the correct response.
> tests: add tests on subscriptions controller

- tests/test_admin.py
Hello, I am interested in working on this OpenCVE project. I wrote these tests to learn more about the project in seeing how it works on a deeper level, and I also wanted to increase the coverage for the admin file. I have made these changes with Unit Tests for Admin that target making changes to passwords based on the existence of a user instance. I appreciate the opportunity to work on this project and hopefully contribute more.
> tests: added test for admin 

- opencve/admin.py
- opencve/templates/admin/change.html
> feat: better JSON diff in admin view

- opencve/controllers/products.py
- opencve/controllers/vendors.py
- tests/controllers/test_products.py
- tests/controllers/test_vendors.py
- tests/views/test_products.py
- tests/views/test_vendors.py
Fixes #153.
P.S.: I apologize for the messed up PRs.
> fix: fix search issues caused by spaces in vendor/product names

- opencve/admin.py
The following small enhacement makes searching in the admin interface much easier.
CveModelView: Added column_filters for updated_at
EventModelView: Added Added column_filters and column_searchable_list support  type, created_at
VendorModelView & ProductModelView: Added column_filters and column_searchable_list support for name
> Admin menu: Added and modified search filters

- opencve/admin.py
See #182
It is not pefect as the names are shown as "<User xyz>"
> Show subscribed users for vendors and products

- opencve/templates/profiles/subscriptions.html
Closes #191 
This PR reworks the way products are displayed in the "My products" table.
I took the example of how to display the products on the "Vendors & Products" page
> My Products - Add vendor name before product name

- opencve/templates/emails/report_message.html
Hi 👋 
I allow myself a modest contribution to redirect to your github repository rather than your old twitter account :)
> fix(email):change link ref to github project

- opencve/templates/base.html
- opencve/templates/emails/report_message.html
> Update template for 2023

- opencve/templates/cve.html
add the CVE.ORG link to the source of informations
> add cve.org link in templates

- web/cves/templates/cves/vendor_list.html
- web/cves/views.py
- web/tests/cves/test_views.py
- web/tests/data/kb/2023/CVE-2023-22490.json
> feat: use case insensitive search for vendors & products

- docker/install.sh
```
$ ./install.sh create-superuser
--> Creating superuser on OpenCVE
Username: nico
Email address: nico@nico.fr
Password:
Password (again):
Superuser created successfully.
--> Get PG ENV variables from docker compose env file
--> Confirm the new user
INSERT 0 1
```
> feat: confirm the created user in the install.sh script

- scheduler/dags/includes/notifiers.py
> fix: send custom headers in webhook notification

- web/changes/views.py
- web/cves/views.py
- web/onboarding/apps.py
- web/onboarding/forms.py
- web/onboarding/middlewares.py
- web/onboarding/urls.py
- web/onboarding/views.py
- web/opencve/conf/base.py
- web/opencve/urls.py
- web/opencve/validators.py
- web/organizations/middlewares.py
- web/organizations/models.py
- web/organizations/templates/organizations/onboarding.html
- web/projects/models.py
- web/projects/views.py
- web/static/css/custom.css
- web/templates/base.html
- web/templates/base_empty.html
- web/templates/head.html
- web/templates/scripts.html
- web/tests/cves/test_views.py
- web/tests/onboarding/test_forms.py
- web/tests/onboarding/test_middlewares.py
- web/tests/onboarding/test_views.py
- web/tests/organizations/test_middlewares.py
- web/tests/organizations/test_models.py
- web/tests/organizations/test_views.py
- web/tests/users/test_views.py
- web/users/models.py
Display a dedicated onboarding view when the user has no organization (typically at the first connection).
Some example data is also created to show OpenCVE features.
> Add the onboarding feature

- scheduler/airflow.cfg.example
- scheduler/dags/includes/notifiers.py
- scheduler/tests/conftest.py
- scheduler/tests/test_notifiers.py
> feat: add start_tls setting for SMTP configuration in the scheduler

- web/cves/templates/cves/statistics.html
- web/static/js/custom.js
- web/templates/base.html
- Rename "CVSS Repartition" to "CVSS Distribution" in both HTML and JavaScript
- Update copyright footer to dynamically display current year using Django template tag
> feat: Update CVSS visualization and copyright year rendering

- scheduler/dags/includes/utils.py
Simple patch for #533 
Let me know if there's anything else you see that needs to be done for this
> fix: add Date header to sent messages

- .gitignore
- scheduler/dags/templates/email_notification.html
- scheduler/dags/templates/email_notification.txt
- scheduler/requirements.txt
- scheduler/tests/data/previews/CVE-CRITICAL-2.json
- scheduler/tests/data/previews/CVE-CRITICAL.json
- scheduler/tests/data/previews/CVE-HIGH.json
- scheduler/tests/data/previews/CVE-LOW.json
- scheduler/tests/data/previews/CVE-MEDIUM.json
- scheduler/tests/data/previews/CVE-NONE.json
- scheduler/tests/requirements.txt
- scheduler/tests/test_notifiers.py
To check the result:
pytest scheduler/tests/test_notifiers.py
> feat: update email notification templates to handle unknown severity cases and add email preview tests
