opencve/context.py, tests/test_context.py
=> fix: display the excerpt list of vendors and products in CVEs listing

opencve/extensions.py, tests/conftest.py, tests/controllers/test_profile.py
The unicity of emails was not checked when the user tried to update his own email in his profile.
This PR also removes the first and last names requirements. It was not practical : if the user wanted to modify his email, the first and last names were required, even if we don't display it anywhere.
=> fix: check if email is unique when editing a profile

opencve/default.cfg, opencve/settings.py, tests/opencve.cfg
Like we discussed in issue #76, this fix aims to ensure compatibility with old `stmp_password` option.
=> #76 : fix "stmp_password" in configuration

requirements.txt
The Pallets Project has upgraded their main projects to major versions : https://palletsprojects.com/blog/flask-2-0-released/
OpenCVE pinned Flask but not its own dependencies, including Click, Werkzeug, ItsDangerous, MarkupSafe and Jinja2. The consequence is that the tests no longer passed (https://github.com/opencve/opencve/runs/2578789549?check_suite_focus=true).
This PR pins these dependencies, so we're sure OpenCVE will still work. Note that a future work has to be done to upgrade these package (ie support Flask 2.0).
=> chore: pin pallets dependencies

opencve/static/js/custom.js
When user clicks the "Subscribe" button at the first time,  $(button).text() gets return value "Subscribe    \n" instead of "Subscribe", which makes the callback function works incorrectly.
=> bugfix: trim() the text of the 'Subscribe' button

opencve/commands/create_user.py, tests/commands/test_create_user.py
The `create-user` command now uses the builtin `click.BadParameter` exception:
```
$ opencve create-user john3 john3@email.fr
Password:
Repeat for confirmation:
Usage: opencve create-user [OPTIONS] USERNAME EMAIL
Error: Invalid value for username: john3 already exists.
```
=> fix: improve error messages in create-user command

opencve/controllers/subscriptions.py, tests/controllers/test_subscriptions.py
In reference to #121 :
This change to the subscriptions controller verifies that the id being passed into the subscriptions POST request is not an invalid ID. It does this by first checking if the ID is passed in is a valid uuid, but then also verifies that it exists within the database if it is a valid uuid. If there is any problem with the id that is passed in, a 400 error is thrown and a JSON response is sent that the id does not exist.
=> fix: Subscribe to invalid ID throws 400 instead of 500 error.

opencve/controllers/home.py, opencve/templates/home.html, tests/views/test_home.py
This PR does 2 things:
- it fixes #133
- it increases the performance of the SQL query
The impact for the user is on the pagination: it's currently a full pagination (1, 2, 3, ...), with this PR it will be **prev** and **next** buttons (see the screenshot).
I used the `.paginate()` function of the `flask_sqlalchemy` package for the pagination (as always in OpenCVE, it works very well). But this function has to do 2 requests: a first one to fetch the objects (see [here](https://github.com/pallets/flask-sqlalchemy/blob/2.x/flask_sqlalchemy/__init__.py#L534)), and a second one to count the total of objects (see [here](https://github.com/pallets/flask-sqlalchemy/blob/2.x/flask_sqlalchemy/__init__.py#L539)).
The second one is just need to have the total number of objects and give it as the …
=> fix: sort the activities in homepage and increase performance of SQL query

opencve/templates/cve.html, opencve/templates/report/new_cve_details.html, opencve/views/cves.py, tests/views/test_cves.py, tests/views/test_reports.py
The CVE view now shows recorded change history using parts of the report view.
This is how it looks: 
Ideas on better design/formatting are welcome!
=> feat: display recorded change history for CVEs

opencve/templates/cve.html
Not a big change, the idea was just to reformat the date to be more easily readable. I took the opportunity to flat the table and display the date as a title.
Before
After
=> feat: display change date in a human format in CVE history

opencve/checks/first_time.py, opencve/constants.py, opencve/forms.py, opencve/migrations/versions/2132d05ea0e2_add_first_time_value_in_event_types_enum.py, opencve/models/users.py, opencve/tasks/alerts.py, opencve/templates/profiles/notifications.html, opencve/views/profile.py, tests/checks/test_cpes.py, tests/checks/test_first_time.py, tests/data/modified_cves/CVE-2018-18074_first_time_1.json, tests/data/modified_cves/CVE-2018-18074_first_time_2.json, tests/tasks/test_alerts.py
Most of the time the NVD creates new CVE without associated CPE, which means the **new_cve** type is not really useful (because no vendor and product are associated, so OpenCVE doesn't have subscribers to alerts).
Then some CPEs are associated, now OpenCVE can triggered an alert with the **cpes** type for the users who subscribed on vendors or products. But these users will receive an alert for each addition/deletion of CPE, even for vendors/products they're not interested in.
With this new **first_time** type the users will be alerted when their subscriptions will appear in an existing CVE. After that, even if the CPE will change, the users with the who check the **first_time** notification option will not be alerted.
This PR closes #157.
=> feat: add the first_time event

opencve/context.py, opencve/controllers/main.py, opencve/templates/home.html
Partially resolve #166 as it add tags in the dashboard view. But it still needs the part where a tag is automatically added when an event is triggered on a subscribed CVE
=> Add tags in dashboard

opencve/commands/imports/cpe.py, opencve/commands/imports/cve.py
Hi all,
To make the data import easier, this PR improve the memory footprint of the import script.
`xml.etree.ElementTree.iterparse()` loads XML tag one by one, and the `.clear()` deletes relations between tags, allowing the garbage collector to remove no more used tag. With this patch, the memory footprint of the CPE XML parsing is almost null :)
Warnings:
- This code does not take the XML hierarchy into account, it takes all the `cpe23-item` tags, We could take it into account, but the code will be more complex :/
- The python `xml` module shows a security warning in the [doc](https://docs.python.org/3/library/xml.etree.elementtree.html) but as untangle is built over it, that's not worst than before. (And in our case, i think we can trust the XML file)
With this patch, I have …
=> Improve import data memory footprint

opencve/templates/base.html
Closes #213 
In this PR, the CSS classes are removed for the login and registration links, so that the links are also displayed on screens with small width. The available space is sufficient so that the class `hidden-xs` can be removed without the need for cosmetic realignment or redesign.
=> Remove class from login/register links

opencve/controllers/alerts.py, opencve/controllers/base.py, opencve/controllers/cves.py, opencve/controllers/cwes.py, opencve/controllers/products.py, opencve/controllers/reports.py, opencve/controllers/tags.py, opencve/controllers/vendors.py, tests/controllers/test_base.py
This PR fixes #237.
Duplicates are shown due to a pagination issue:
- when the NVD updates some CVEs the `lastModifiedDate` may be the same
- OpenCVE saves this information in the `updated_at` field
- so some CVEs have the same `updated_at` value, raising this issue when pagination is used
Ordering the CVEs by updated_at and CVE ID fixes it.
=> fix: remove duplicates items when pagination is used

requirements.txt
Thanks to @TexGG who found the solution, here is a patch to fix the following issue:
- https://github.com/opencve/opencve/issues/239
- https://github.com/opencve/opencve/issues/277
- https://github.com/opencve/opencve/issues/198
=> fix: upgrade jsmin package to fix a dependency issue

docker/install.sh
Makes the install script work on Unix systems which do not have the exact same GNU xargs binary as the initial author had (incompatible `-d` parameter).
=> Fixes #426 - xargs using exotic `-d`parameter not available on every xargs derivate

docker/conf/.env.example
This makes use of the values set for variables `POSTGRES_USER` and `POSTGRES_PASSWORD` later in the `.env` file to make the docs work without additional steps.
=> Fixes #432

docker/conf/default.conf.template.example, docker/docker-compose.yaml, docker/install.sh
This is a suggestion to overwrite `/etc/nginx/conf.d/default.conf`.
fixes #439 
- enter docker nginx with `docker exec -it nginx /bin/sh`
- run `nginx -T`
- observe following configuration
```
server {
listen       80;
listen  [::]:80;
server_name  localhost;
#access_log  /var/log/nginx/host.access.log  main;
location / {
root   /usr/share/nginx/html;
index  index.html index.htm;
}
#error_page  404              /404.html;
#
error_page   500 502 503 504  /50x.html;
location = /50x.html {
root   /usr/share/nginx/html;
}
#
#location ~ \.php$ {
#}
#
#location ~ \.php$ {
#}
#
#location ~ /\.ht {
#}
}
```
which matches localhost instead of the opencve webserver.
replace `nginx` default server conf by an (essentially) empty file.
=> fix: added overwriting template for nginx default.conf (#439)

web/cves/templates/cves/cve_detail.html
Fix #442 
A lot of CVE descriptions start with non A-Z letters:
```
cve_id      |                                                      left
------------------+----------------------------------------------------------------------------------------------------------------
CVE-1999-0417    | 64 bit Solaris 7 procfs allows local users to perform a denial of service.
CVE-1999-0572    | .reg files are associated with the Windows NT registry editor (regedit), making the registry suscept
CVE-1999-1318    | /usr/5bin/su in SunOS 4.1.3 and earlier uses a search path that includes the current working directo
CVE-1999-1336    | 3Com HiPer Access Router Card (HiperARC) 4.0 through 4.2.29 allows remote attackers to cause a denia
CVE-1999-1383    | (1) bash before 1.14.7, and (2) tcsh 6.05 allow local …
```
=> refactor: remove the dropcap css class in CVE details page

scheduler/requirements.txt
This PR downgrades the Celery Airflow provider to a previous version due to a bug identified in the current release. The issue affects task execution reliability:
```
...
File "/.../.local/lib/python3.11/site-packages/airflow/providers/celery/cli/celery_command.py", line 234, in worker
_run_command_with_daemon_option(
File "/.../.local/lib/python3.11/site-packages/airflow/providers/celery/cli/celery_command.py", line 51, in _run_command_with_daemon_option
raise AirflowOptionalProviderFeatureException(
airflow.exceptions.AirflowOptionalProviderFeatureException: Failed to import run_command_with_daemon_option. This feature is only available in Airflow versions >= 2.8.0
```
The downgrade is a temporary measure until the upstream bug is resolved (related issue can be found here: …
=> chore: downgrade Celery Airflow provider due to a bug

web/users/forms.py
Set the autofocus on the username for the login and registration form, in order to simplify the login. Especially when using password managers it's more convenient.
=> Add autofocus for login and registration form

docker/docker-compose.yaml, docker/install.sh
I suggest that we remove container names/named containers from docker-compose.yaml and install.sh so that one can have multiple installations on the same docker host.
The only external dependency on having `container_name:` in the docker-compose.yaml file, is so that something (say, install.sh) can integrate with a specific running container. By just adding "compose" to the `docker` command in the install.sh script, we get rid of the hard coded dependency.
In some (say my) environment, I might want to use those names for other continers, and/or I would like to run multiple instances of the opencve application for whatever reason.
The fix:
* Remove the container_names from the docker compose file
* Fix the install.sh script so that it can interact with the continers properly
=> removing container names/named containers from docker-compose.yaml
